### ISSUE TITLE
help output needs minor update

### ISSUE THREAD

**Issue by jnmaloof** [mfcovington/auto_barcode#4]
If one runs the perl script without proper input a nice help message is returned.  There is a small error, however.

The Examples do not tell you to include the --id tag, but that appears to be mandatrory.  The README is correct.

**Comment by mfcovington** [comment]
Tried to add them to a gist, and link them from here to have a record of them, but GitHub auto-converts them to the 'normal' line ending! Anyway, I've fixed the problem based one of the files you emailed me (`0.sample_barcode_key_GH_lane_7_mike_style.txt`).

However, the other file (`0.sample_barcode_key_GC_lane_6_mike_style.txt`) fails because it contains spaces instead of a tab to delimit the columns.
